name: Terraform Destroy
description: Terraform Destroys in SUBDIRS
runs:
  using: "composite"
  steps:
    - run: |
        cd ${SUBDIR}
        terraform init --backend-config=bucket=${PROJECT_NAME}-${MODULE_NAME}-terraform-state
        terraform destroy -var "project-name=${PROJECT_NAME}" -var "module-name=${MODULE_NAME}" -auto-approve
      shell: bash