name: Terraform Init & Apply
description: Runs terraform init and apply
runs:
  using: "composite"
  steps:
    - run: |
        cd ${SUBDIR} && \
        terraform init && \
        terraform apply -var "project-name=${PROJECT_NAME}" -var "module-name=${MODULE_NAME}" -auto-approve
      shell: bash