name: Create a Terraform Workspace if not exists
description: Creates a Terraform Workspace if not exists
runs:
  using: "composite"
  steps:
    - run: |
        cd ${SUBDIR}
        TF_WORKSPACE=default terraform init
        terraform workspace new $TF_WORKSPACE || echo "Workspace already exists"
      shell: bash