name: 'Base'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production
    container:
      image: docker.pkg.github.com/kelseymok/terraform-workspace/terraform-workspace:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Assume Role
      run: assume-role twdu-germany-github-runner-aws

    - name: Terraform Init
      run: |
        cd base && \
        terraform init

    - name: Terraform Plan
      run: |
        cd base && \
        terraform plan -var-file=variables.tfvars

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        cd base && \
        terraform apply -var-file=variables.tfvars -auto-approve
