name: 'PL/KM'

env:
  PROJECT_NAME: twdu-germany
  MODULE_NAME: pl-km-test
  TF_WORKSPACE: pl-km-test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  base:
    name: 'Base Terraform'
    runs-on: self-hosted
    environment: production
    container:
      image: docker.pkg.github.com/kelseymok/terraform-workspace/terraform-workspace:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Assume Role
      run: assume-role twdu-germany-github-runner-aws

    - name: Create a Terraform Workspace if not exists
      run: |
        set -ex
        cd base && \
        TF_WORKSPACE=default terraform init && \
        if [ ! $(terraform workspace select $TF_WORKSPACE) ]; then terraform workspace new $TF_WORKSPACE; fi

#    - name: Terraform Init & Destroy
#      run: |
#        cd base && \
#        terraform init && \
#        terraform destroy -var-file=variables.tfvars -auto-approve

    - name: Terraform Init & Apply
      run: |
        cd base && \
        terraform init && \
        terraform apply -var-file=variables.tfvars -auto-approve
  data-ingestion:
    name: 'Data Ingestion'
    runs-on: self-hosted
    environment: production
    needs: ["base"]
    container:
      image: docker.pkg.github.com/kelseymok/terraform-workspace/terraform-workspace:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assume Role
        run: assume-role twdu-germany-github-runner-aws

#      - name: Terraform Init & Destroy
#        run: |
#          cd data-ingestion && \
#          TF_WORKSPACE=default terraform init && \
#          TF_WORKSPACE=default terraform destroy -var-file=variables.tfvars -auto-approve

      - name: Terraform Init & Apply
        run: |
          cd data-ingestion && \
          terraform init && \
          terraform apply -var-file=variables.tfvars -auto-approve

  data-transformation:
    name: 'Data Transformation'
    runs-on: self-hosted
    environment: production
    needs: [ "base" ]
    container:
      image: docker.pkg.github.com/kelseymok/terraform-workspace/terraform-workspace:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assume Role
        run: assume-role twdu-germany-github-runner-aws

#      - name: Terraform Init & Destroy
#        run: |
#          cd data-ingestion && \
#          TF_WORKSPACE=default terraform init && \
#          TF_WORKSPACE=default terraform destroy -var-file=variables.tfvars -auto-approve

      - name: Terraform Init & Apply
        run: |
          cd data-transformation && \
          terraform init && \
          terraform apply -var-file=variables.tfvars -auto-approve
