name: Docker Build and Push Image

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-push-dev-container.yml'

jobs:
  build-and-push-image:
    runs-on: self-hosted
    name: Docker Build, Tag, Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/kelseymok/twdu-europe/dev-container:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
